name: linux CI
on: 
  push:
    branches: [main,master]
  pull_request:
    branches: [main, master]
jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - name: Code checkout
      uses: actions/checkout@v4
    - name: Compiler setting
      run: |
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
        else
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
        fi
    - name: Build with CMake
      run: |
        cmake -S . -B build
        cmake --build build
