name: windows CI
on: 
  push:
    branches: [main,master]
  pull_request:
    branches: [main, master]
jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v4
    - name: Build with CMake
      run: |
        cmake -S . -B build
        cmake --build build
